/*
 * NAMA  : Fiona Avila Putri
 * NIM   : 10119013
 * KELAS : IF1 2019/2020
 */
package kemahasiswaan_10119001_10119013;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Fiona Avila
 */
public class frm_daftar extends javax.swing.JFrame {

    /**
     * Creates new form frm_daftar
     */
    
    koneksi dbsetting;
    String driver, database, user, pass;
    
    public frm_daftar() {
        initComponents();
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_judul_daftar = new javax.swing.JLabel();
        lbl_daftar_username = new javax.swing.JLabel();
        lbl_daftar_password = new javax.swing.JLabel();
        lbl_daftar_nama = new javax.swing.JLabel();
        txt_daftar_username = new javax.swing.JTextField();
        txt_daftar_password = new javax.swing.JTextField();
        txt_daftar_nama = new javax.swing.JTextField();
        btn_back_login = new javax.swing.JButton();
        btn_daftar_akun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(209, 209, 229));

        lbl_judul_daftar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        lbl_judul_daftar.setText("DAFTAR");

        lbl_daftar_username.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbl_daftar_username.setText("Username");

        lbl_daftar_password.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbl_daftar_password.setText("Password");

        lbl_daftar_nama.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbl_daftar_nama.setText("Nama");

        txt_daftar_username.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        txt_daftar_password.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        txt_daftar_nama.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        btn_back_login.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_back_login.setText("Kembali ke halaman login");
        btn_back_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_back_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_back_loginMouseExited(evt);
            }
        });
        btn_back_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_loginActionPerformed(evt);
            }
        });

        btn_daftar_akun.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_daftar_akun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/add.png"))); // NOI18N
        btn_daftar_akun.setText("Daftar");
        btn_daftar_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_daftar_akunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_daftar_akunMouseExited(evt);
            }
        });
        btn_daftar_akun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftar_akunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_daftar_password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_daftar_password, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_daftar_username)
                        .addGap(18, 18, 18)
                        .addComponent(txt_daftar_username, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_daftar_nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_daftar_akun)
                            .addComponent(txt_daftar_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_judul_daftar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back_login)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_judul_daftar)
                    .addComponent(btn_back_login))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_daftar_username)
                    .addComponent(txt_daftar_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_daftar_password)
                    .addComponent(txt_daftar_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_daftar_nama)
                    .addComponent(txt_daftar_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btn_daftar_akun)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_daftar_akunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftar_akunMouseEntered
        btn_daftar_akun.setBackground(new java.awt.Color(128,136,203));
        btn_daftar_akun.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_daftar_akunMouseEntered

    private void btn_daftar_akunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftar_akunMouseExited
        btn_daftar_akun.setBackground(new java.awt.Color(255, 255, 255));
        btn_daftar_akun.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_daftar_akunMouseExited

    private void btn_back_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_back_loginMouseEntered
        btn_back_login.setBackground(new java.awt.Color(128,136,203));
        btn_back_login.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_back_loginMouseEntered

    private void btn_back_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_back_loginMouseExited
        btn_back_login.setBackground(new java.awt.Color(255, 255, 255));
        btn_back_login.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_back_loginMouseExited

    private void btn_back_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_loginActionPerformed
        frm_login l = new frm_login();
        l.setVisible(true);
    }//GEN-LAST:event_btn_back_loginActionPerformed

    private void btn_daftar_akunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftar_akunActionPerformed
        try{
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(
                                    database,
                                    user,
                                    pass);
            Statement stt = kon.createStatement();
            String SQL = "INSERT INTO t_user(Username, Password, Nama) "
                    + "VALUES ('"+txt_daftar_username.getText()+"', "
                    + "'"+txt_daftar_password.getText()+"', "
                    + "'"+txt_daftar_nama.getText()+"');";   
            stt.close();
            kon.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Gagal Mendaftar!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_daftar_akunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back_login;
    private javax.swing.JButton btn_daftar_akun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_daftar_nama;
    private javax.swing.JLabel lbl_daftar_password;
    private javax.swing.JLabel lbl_daftar_username;
    private javax.swing.JLabel lbl_judul_daftar;
    private javax.swing.JTextField txt_daftar_nama;
    private javax.swing.JTextField txt_daftar_password;
    private javax.swing.JTextField txt_daftar_username;
    // End of variables declaration//GEN-END:variables
}
